version: "3.7"

services:
  app:
    image: devconf5296/wowtown_backend:0.1
    ports:
      - 81:8080
    working_dir: /deploy/wowtown
    depends_on:
      - redis
    restart: always

  redis:
    image: redis
    container_name: redis
    restart: always
    ports:
      - 6379:6379
