version: "3.7"

services:
  app:
    image: devconf5296/wowtown_backend:latest
    ports:
      - 443:443 # Support HTTPS
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql_db:3306/wow_town?useSSL=false&characterEncoding=UTF-8&serverTimeZone=UTC&&allowPublicKeyRetrieval=true
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - SSL_PKCS12_PASSWORD=${SSL_PKCS12_PASSWORD}
      - SSL_PKCS12_STORE=${SSL_PKCS12_STORE}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRETE_KEY=${AWS_SECRETE_KEY}
    working_dir: /deploy/wowtown_backend
    depends_on:
      - redis
      - mysql
    restart: on-failure
    networks:
      - app-mysql-network

  redis:
    image: redis
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    networks:
      - app-mysql-network


  mysql:
    image: mysql:8.0
    container_name: mysql_db
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=wow_town
      - MYSQL_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=UTC
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --lower_case_table_names=1
    volumes:
      - ~/mysql:/var/lib/mysql
    networks:
      - app-mysql-network

networks:
  app-mysql-network:
