version: "3.7"

services:
  app:
    image: devconf5296/wowtown_backend:0.1
    ports:
      - 81:8080
    working_dir: /deploy/wowtown
    depends_on:
      - redis
      - mysql
    restart: always

  redis:
    image: redis
    container_name: redis
    restart: always
    ports:
      - 6379:6379


  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=wow_town
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=UTC
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --lower_case_table_names=1
    volumes:
      - ~/mysql:/var/lib/mysql
