spring:
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB

  mail:
    host: smtp.gmail.com
    port: 587
    username: devconf5296@gmail.com
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  redis:
    host: redis
    port: 6379

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: root
    password: wowTown123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    database: mysql

  decorator:
    datasource:
      p6spy.enable-logging: true

server:
  port: 443
  ssl:
    enabled: true
    enabled-protocols:
      - TLSv1.1
      - TLSv1.2
    key-store: ${SSL_PKCS12_STORE}
    key-store-type: PKCS12
    key-store-password: ${SSL_PKCS12_PASSWORD}

cloud:
  aws:
    stack:
      auto: false
    s3:
      bucket: wowotown
    region:
      static: ap-northeast-2
    credentials:
      accessKey: ${AWS_ACCESS_KEY_ID}
      secretKey: ${AWS_SECRETE_KEY}

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error

