spring:
  redis:
    host: localhost
    port: 6379
    password: test1234

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/wow_town?serverTimezone=UTC&characterEncoding=UTF-8
      username: root
      password: wowTown123

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true

  decorator:
    datasource:
      p6spy.enable-logging: true